### ISSUE TITLE
[Feature request] Add support to torch.cuda.DoubleTensor

### ISSUE THREAD

**Issue by Lotayou** [KinglittleQ/torch-batch-svd#1]
Thanks for your amazing work! I'm wondering if will you add support to torch.float64, a.k.a. DoubleTensor?

**Comment by KinglittleQ** [comment]
I will work on it when I am free.

**Comment by Lotayou** [comment]
Thanks. Keep up the good work bro:)

**Comment by justanhduc** [comment]
@Lotayou just fyi, `torch.float64` is supported from the last commit.

**Comment by KinglittleQ** [comment]
Closed it because the requested feature is supported now.
