### ISSUE TITLE
Need multi GPUs compatibility: RuntimeError: Expected cudaSuccess == status_memcpy to be true, but got false.

### ISSUE THREAD

**Issue by ventusff** [KinglittleQ/torch-batch-svd#11]
## Traceback and info
Got `RuntimeError` when running with input tensor on device `cuda:1` with size `[200,3,3]`. 

Python traceback: 
```
RuntimeError: Expected cudaSuccess == status_memcpy to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.)
... unrelated tracebacks
  File "/data/ai_ws/DIT-NERF-DEV/models/deformation.py", line 145, in get_minibatch_deformation_loss
    _, s, _ = svd(J)
  File "/home/ventus/anaconda3/envs/habitat/lib/python3.6/site-packages/torch_batch_svd-1.0.0-py3.6-linux-x86_64.egg/torch_batch_svd/batch_svd.py", line 38, in forward
    _c.batch_svd_forward(input, U, S, V, True, 1e-7, 100, is_double)
```

Some environment info:
```
OS: ubuntu 16
torch==1.7.1, installed from pip
cuda10.2 with dual GTX1080 # notice here
python3.6 
```

## Rough debugging
The error was a failed `TORCH_CHECK` in https://github.com/KinglittleQ/torch-batch-svd/blob/fabe8122fc81fadd06f0b19db78f47286eb57bd1/torch_batch_svd/csrc/torch_batch_svd.cpp#L84

I've done some simple `std::cout` debugging before the line (not familiar with cuda cpp programing), and found out it seems to be related with calling `cudaMemcpy` on addresses in different graphic cards (I'm not sure, but see my workaround at the end which may prove this):

```
batchsize: 200
hinfo.data(): 0x55daa2828380
info_ptr.get(): 0x7fa97e881800
status_memcpy: 700
cudaSuccess: 0
```
The input tensor `J` is originally stored on `cuda:1` device.
According to cuda includes `/usr/local/cuda-10.2/targets/x86_64-linux/include/driver_types.h`, `cudaError_t` with `700` value means:

```c
    /**
     * The device encountered a load or store instruction on an invalid memory address.
     * This leaves the process in an inconsistent state and any further CUDA work
     * will return the same error. To continue using CUDA, the process must be terminated
     * and relaunched.
     */
    cudaErrorIllegalAddress               =     700,
```

## Current workaround
After moving the input tensor to `cuda:0` device temporarily, there's no error again.

**Comment by KinglittleQ** [comment]
Could you give a simple example to reproduce the error?

**Comment by ventusff** [comment]
HI @KinglittleQ ,
Yes, sure
```python
import torch
from torch_batch_svd import svd
a = torch.randn(200,3,3).to("cuda:1")
u, s, v = svd(a)
```

**Comment by ventusff** [comment]
BTW, I've tried add 
```c
cudaSetDevice(a.get_device());
```
at the begging of `batch_svd_forward` function, e.g. https://github.com/ventusff/torch-batch-svd/commit/611dd63e5c3f6ce7564898fc13dd34bdfb641e84
seems to fix this issue for good, but I do not know whether this is a valid programing style in cuda programming or are there any further problems with it.

**Comment by KinglittleQ** [comment]
It is fixed. The latest code should be able to run on all GPUs now.

**Comment by ventusff** [comment]
Cool, thanks
