### ISSUE TITLE
Replacing includes of THC/THC.h to ATen/ATen.h

### ISSUE THREAD

**Issue by gerwang** [KinglittleQ/torch-batch-svd#20]
Hello, 

I'm using pytorch 1.11.0. Seems that it doesn't have THC/THC.h anymore, and will cause a compilation error.

After replacing the include with ` #include <ATen/ATen.h>`, the project can be compiled.

Please fix it, maybe by detecting the pytorch version?

**Comment by KinglittleQ** [comment]
Thank you very much for your report. I will take some time to fix it.
