### ISSUE TITLE
Fail to install the package

### ISSUE THREAD

**Issue by smiles724** [KinglittleQ/torch-batch-svd#23]
Hi, I am new to your packages, and it reported error when running the setup.py.
![image](https://user-images.githubusercontent.com/39299863/194757060-34bbebee-b960-4d55-96bc-8904c0ba83df.png)

Can you please give any suggestions or detailed introductions on how to install the torch_batch_svd successfully?

Best,

**Comment by KinglittleQ** [comment]
The setup failed since the folder is not a git folder. Please git clone it: 

```
git clone git@github.com:KinglittleQ/torch-batch-svd.git
```

**Comment by smiles724** [comment]
It works! 

However, Following your guidance, I ran into another type of error like this:
![image](https://user-images.githubusercontent.com/39299863/194798370-1cb8cc25-7ae8-4c61-80dd-0f564b8a30b2.png)

**Comment by KinglittleQ** [comment]
Please import torch_batch_svd in another directory (not in torch_batch_svd/).

For example:

```
cd tests
python -c "import torch_batch_svd"
```

**Comment by smiles724** [comment]
Thanks! The package runs successfully. Great implemetation!
