### ISSUE TITLE
Error on PyTorch 1.0.1 and Cuda 9

### ISSUE THREAD

**Issue by Jerrypiglet** [KinglittleQ/torch-batch-svd#3]
Hi there,

I am seeing the error when I was running the test.py:

Traceback (most recent call last):
  File "test.py", line 33, in <module>
    test()
  File "test.py", line 23, in test
    print((U[0].abs() - u.abs()).sum())
RuntimeError: The size of tensor a (3) must match the size of tensor b (9) at non-singleton dimension 1

I am on PyTorch 1.0.1 and Cuda 9, Python 3.6 if that helps.

Thanks!

**Comment by KinglittleQ** [comment]
Please try to set `some=True`  at [line 16](https://github.com/KinglittleQ/torch-batch-svd/blob/bd056473e8b8b276b18f0566d92667deeef8e569/test.py#L16).

**Comment by Jerrypiglet** [comment]
@KinglittleQ I see. Thanks!
