### ISSUE TITLE
Error with shape [8, 2000, 9]

### ISSUE THREAD

**Issue by Jerrypiglet** [KinglittleQ/torch-batch-svd#4]
Hi there,

I am gettign an error trying to run 

batch_svd(XX)

where XX is of shape [8, 2000, 9], where 8 is the batch dimension. The error trace is as follows:

File "/home/ruizhu/Documents/Projects/kitti_instance_RGBD_utils/dsac_tools/utils_F.py", line 188, in _E_from_XY_batch
    U, D, V = batch_svd(XX)
  File "/home/ruizhu/Documents/Projects/kitti_instance_RGBD_utils/deepSfm_ori/torch-batch-svd/batch_svd.py", line 36, in batch_svd
    return BatchSVDFunction.apply(x)
  File "/home/ruizhu/Documents/Projects/kitti_instance_RGBD_utils/deepSfm_ori/torch-batch-svd/batch_svd.py", line 9, in forward
    U0, S, V0 = torch_batch_svd.batch_svd_forward(x, True, 1e-7, 100)
RuntimeError: matrix row should be <= 32 (batch_svd_forward at torch_batch_svd.cpp:66)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f92f9f13021 in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f92f9f128ea in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: torch_batch_svd::batch_svd_forward(at::Tensor, bool, double, int) + 0xe96 (0x7f92e38855f6 in /home/ruizhu/Documents/Projects/kitti_instance_RGBD_utils/deepSfm_ori/torch-batch-svd/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x18fcd (0x7f92e3894fcd in /home/ruizhu/Documents/Projects/kitti_instance_RGBD_utils/deepSfm_ori/torch-batch-svd/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x165c5 (0x7f92e38925c5 in /home/ruizhu/Documents/Projects/kitti_instance_RGBD_utils/deepSfm_ori/torch-batch-svd/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0x581 (0x7f9334451ab1 in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #49: __libc_start_main + 0xe7 (0x7f9347ad5b97 in /lib/x86_64-linux-gnu/libc.so.6)

Any ideas? Thanks!

**Comment by Jerrypiglet** [comment]
FYI after I commenting L66 and L68 in torch_batch_svd.cpp, the errors are now:

RuntimeError:  (batch_svd_forward at torch_batch_svd.cpp:125)
frame #0: std::function<std::string ()>::operator()() const + 0x11 (0x7f5c04f29021 in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x2a (0x7f5c04f288ea in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #2: torch_batch_svd::batch_svd_forward(at::Tensor, bool, double, int) + 0xf3c (0x7f5c02d3a68c in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x18d6d (0x7f5c02d49d6d in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x16365 (0x7f5c02d47365 in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0x581 (0x7f5c3f467ab1 in /home/ruizhu/anaconda3/envs/kitti_py36/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #28: __libc_start_main + 0xe7 (0x7f5c52607b97 in /lib/x86_64-linux-gnu/libc.so.6)

**Comment by KinglittleQ** [comment]
CuSolver only supports matrices of which the dimension is smaller than 32.

**Comment by Jerrypiglet** [comment]
@KinglittleQ Thanks for the explanation! Is there any chance we can get around this?

**Comment by KinglittleQ** [comment]
I think it's a little hard. In your case, matrices with the shape of [8, 2000, 9] can simply use a loop to slove.

**Comment by Jerrypiglet** [comment]
> I think it's a little hard. In your case, matrices with the shape of [8, 2000, 9] can simply use a loop to slove.

Thanks for the explanation! I see. It would still be good see it working somehow because if we implement SVD on large matrices with a loop, it will significantly diminish the speed advantage of batch_svd over torch.svd. Hope to see this solved in the future!

**Comment by matteo-ronchetti** [comment]
Maybe you could use the fact that if
![svd](https://latex.codecogs.com/gif.latex?%5Cdpi%7B120%7D%20%5Clarge%20A%20%3D%20U%20%5CSigma%20V%5ET)
then
![svd](https://latex.codecogs.com/gif.latex?%5Cdpi%7B120%7D%20%5Clarge%20A%5ET%20A%20%3D%20V%20%5CSigma%5E2%20V%5ET%20%5Cin%20%5Cmathbb%7BR%7D%5E%7B9%20%5Ctimes%209%7D%20%5C%3B%20%5C%3B%5C%3B%20%5C%3B%5C%3B%20%5C%3B%5C%3B%20%5C%3B%5C%3B%20%5C%3B%5C%3B%20%5C%3B%20U%20%3D%20A%20V%20%5CSigma%5E%7B-1%7D)

In code you could do
```python
C = torch.einsum("bci,bcj->bij", A, A) # C will have shape (8, 9, 9)
_, S2, V = batch_svd(C)
S = torch.sqrt(S2)
U = torch.einsum("bci,bid,d->bcd", A, V, 1/S)
```
