### ISSUE TITLE
Full rank checking to avoid 'nan' in backward

### ISSUE THREAD

**Issue by yongheng1991** [KinglittleQ/torch-batch-svd#5]
Hi,
Thanks for the code.
I have a question, the backward will turns out to have 'NaN' when the matrix is not full rank. This is also mentioned in the official SVD of pytorch. (https://pytorch.org/docs/stable/torch.html?highlight=svd#torch.svd)

Have u ever considered how to solve this problem?
Best.

**Comment by KinglittleQ** [comment]
Not yet now.

**Comment by WeiWangTrento** [comment]
Check this paper: Backpropagation-Friendly Eigendecomposition
https://github.com/WeiWangTrento/Power-Iteration-SVD
