### ISSUE TITLE
error when test

### ISSUE THREAD

**Issue by liwenssss** [KinglittleQ/torch-batch-svd#6]
hi, @KinglittleQ , I run the set.py and got the following log:
```
running install
running bdist_egg
running egg_info
writing torch_batch_svd.egg-info/PKG-INFO
writing dependency_links to torch_batch_svd.egg-info/dependency_links.txt
writing top-level names to torch_batch_svd.egg-info/top_level.txt
reading manifest file 'torch_batch_svd.egg-info/SOURCES.txt'
writing manifest file 'torch_batch_svd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for torch_batch_svd.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_batch_svd.py to torch_batch_svd.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.torch_batch_svd.cpython-36: module references __file__
creating 'dist/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg
creating /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg
Extracting torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg to /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages
Adding torch-batch-svd 0.0.0 to easy-install.pth file

Installed /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg
Processing dependencies for torch-batch-svd==0.0.0
Finished processing dependencies for torch-batch-svd==0.0.0
```
it seems that I setup successfully.But when I run the test.py, I got the error:
```
Traceback (most recent call last):
  File "test.py", line 33, in <module>
    test()
  File "test.py", line 12, in test
    U, S, V = batch_svd(a)
  File "/home/liwensh/code/torch-batch-svd/batch_svd.py", line 36, in batch_svd
    return BatchSVDFunction.apply(x)
  File "/home/liwensh/code/torch-batch-svd/batch_svd.py", line 9, in forward
    U0, S, V0 = torch_batch_svd.batch_svd_forward(x, True, 1e-7, 100)
RuntimeError: Expected CUSOLVER_STATUS_SUCCESS == status to be true, but got false.  (Could this error message be improved?  If so, please report an enhancement request to PyTorch.) (batch_svd_forward at torch_batch_svd.cpp:127)
frame #0: c10::Error::Error(c10::SourceLocation, std::string const&) + 0x33 (0x7f2d44959273 in /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch/lib/libc10.so)
frame #1: torch_batch_svd::batch_svd_forward(at::Tensor, bool, double, int) + 0x1344 (0x7f2d9b8659d4 in /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #2: <unknown function> + 0x1efef (0x7f2d9b878fef in /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #3: <unknown function> + 0x1f4ce (0x7f2d9b8794ce in /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
frame #4: <unknown function> + 0x1c960 (0x7f2d9b876960 in /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so)
<omitting python frames>
frame #11: THPFunction_apply(_object*, _object*) + 0x9df (0x7f2d8ef7a91f in /home/liwensh/anaconda3/envs/densebody/lib/python3.6/site-packages/torch/lib/libtorch_python.so)
frame #28: __libc_start_main + 0xf0 (0x7f2d9dd6e830 in /lib/x86_64-linux-gnu/libc.so.6)
```

Any advice can you give me ? Thanks for your contributing!!!

**Comment by liwenssss** [comment]
by the way, I am using python 3.7.4, cuda9.0, pytorch 1.0.0

**Comment by liwenssss** [comment]
anyone can give me some advice? need help plz

**Comment by WeiWangTrento** [comment]
Have you solved the problem?
I have a similar error. It seems to have been installed successfully, but I have problem to import it.
>>>import torch_batch_svd
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
ImportError: /cvlabdata2/home/wei/anaconda3/lib/libcusolver.so.9.0: undefined symbol: GOMP_critical_end

The following is what I see after running 'python setup.py install'
running install
running bdist_egg
running egg_info
writing torch_batch_svd.egg-info/PKG-INFO
writing dependency_links to torch_batch_svd.egg-info/dependency_links.txt
writing top-level names to torch_batch_svd.egg-info/top_level.txt
reading manifest file 'torch_batch_svd.egg-info/SOURCES.txt'
writing manifest file 'torch_batch_svd.egg-info/SOURCES.txt'
installing library code to build/bdist.linux-x86_64/egg
running install_lib
running build_ext
creating build/bdist.linux-x86_64/egg
copying build/lib.linux-x86_64-3.6/torch_batch_svd.cpython-36m-x86_64-linux-gnu.so -> build/bdist.linux-x86_64/egg
creating stub loader for torch_batch_svd.cpython-36m-x86_64-linux-gnu.so
byte-compiling build/bdist.linux-x86_64/egg/torch_batch_svd.py to torch_batch_svd.cpython-36.pyc
creating build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/PKG-INFO -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/SOURCES.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/dependency_links.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
copying torch_batch_svd.egg-info/top_level.txt -> build/bdist.linux-x86_64/egg/EGG-INFO
writing build/bdist.linux-x86_64/egg/EGG-INFO/native_libs.txt
zip_safe flag not set; analyzing archive contents...
__pycache__.torch_batch_svd.cpython-36: module references __file__
creating 'dist/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg' and adding 'build/bdist.linux-x86_64/egg' to it
removing 'build/bdist.linux-x86_64/egg' (and everything under it)
Processing torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg
removing '/cvlabdata2/home/wei/anaconda3/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg' (and everything under it)
creating /cvlabdata2/home/wei/anaconda3/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg
Extracting torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg to /cvlabdata2/home/wei/anaconda3/lib/python3.6/site-packages
torch-batch-svd 0.0.0 is already the active version in easy-install.pth

Installed /cvlabdata2/home/wei/anaconda3/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg
Processing dependencies for torch-batch-svd==0.0.0
Finished processing dependencies for torch-batch-svd==0.0.0
