### ISSUE TITLE
Undefined symbol

### ISSUE THREAD

**Issue by abcdxyzpqrst** [KinglittleQ/torch-batch-svd#7]
Hello, thanks for nice library!

I want to install torch-batch-svd with PyTorch v1.2, but I got some following errors

torch_batch_svd.cpython-36m-x86_64-linux-gnu.so: undefined symbol: _ZN2at19UndefinedTensorImpl10_singletonE

How can I fix it?

**Comment by abcdxyzpqrst** [comment]
I've fixed it

**Comment by moranli19** [comment]
Sorry to bother. 
I meet the similar ( problem 'undefined symbol: cusolverDnDestroyGesvdjInfo'), can you share your solution? 
Thanks for any reply~! @abcdxyzpqrst 

install env: 
Ubuntu16, cuda=10.0, pytorch=1.6.0
`    from . import _c
E   ImportError: /opt/conda/envs/DNF_2/lib/python3.6/site-packages/torch_batch_svd-0.0.0-py3.6-linux-x86_64.egg/torch_batch_svd/_c.cpython-36m-x86_64-linux-gnu.so: undefined symbol: cusolverDnDestroyGesvdjInfo`

**Comment by abcdxyzpqrst** [comment]
My problem was that when I tried to reinstall in another virtualenv using already installed torch-batch-svd package.
So, after deleting all the build-related files (such as build folder) and reinstalling, the problem disappeared.

But your error message looks a little bit different since you have "cusolver" related problems.
