### ISSUE TITLE
Maximum size of the matrix

### ISSUE THREAD

**Issue by littlesun0727** [KinglittleQ/torch-batch-svd#9]
I really love this library. But when I try to test with 

A = torch.randn(1000,100,100)
U,S,D=svd(A)

It returns **_AssertionError: This implementation only supports matrices having dims smaller than 32_**

It seems that this package only supports decomposed matrix A with small size. Can I use this package if the size of matrix is really large?

**Comment by KinglittleQ** [comment]
As cuSolver only supports matrices with dimensions smaller than32, so this repo does not deal with large matrices.
